// <auto-generated />
namespace UniversityProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ClassRoomV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassRoomV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202002101537386_ClassRoomV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
